/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;

/**
 *
 * @author crist
 */
public class SpaceStationView extends javax.swing.JPanel {

    /**
     * Creates new form SpaceStationView
     */
    public SpaceStationView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre_estacion = new javax.swing.JLabel();
        titulo_ataque = new javax.swing.JLabel();
        titulo_defensa = new javax.swing.JLabel();
        titulo_combustible = new javax.swing.JLabel();
        titulo_medallas = new javax.swing.JLabel();
        ataque = new javax.swing.JLabel();
        defensa = new javax.swing.JLabel();
        combustible = new javax.swing.JLabel();
        medallas = new javax.swing.JLabel();
        pendingDamage = new javax.swing.JPanel();
        weaponsMounted = new javax.swing.JScrollPane();
        panelWeaponsMounted = new javax.swing.JPanel();
        shieldsMounted = new javax.swing.JScrollPane();
        panelShieldsMounted = new javax.swing.JPanel();
        panelHangarStation = new javax.swing.JPanel();
        mountButton = new javax.swing.JButton();
        discardButton = new javax.swing.JButton();
        discardHangarButton = new javax.swing.JButton();

        nombre_estacion.setBackground(new java.awt.Color(0, 255, 0));
        nombre_estacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre_estacion.setText("NOMBRE ESTACIÓN");

        titulo_ataque.setText("Potencia de ataque :");

        titulo_defensa.setText("Potencia de Defensa :");

        titulo_combustible.setText("Nivel de combustible :");

        titulo_medallas.setText("Medallas :");

        ataque.setText("jLabel5");

        defensa.setText("jLabel6");

        combustible.setText("jLabel7");

        medallas.setText("jLabel8");

        javax.swing.GroupLayout pendingDamageLayout = new javax.swing.GroupLayout(pendingDamage);
        pendingDamage.setLayout(pendingDamageLayout);
        pendingDamageLayout.setHorizontalGroup(
            pendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );
        pendingDamageLayout.setVerticalGroup(
            pendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelWeaponsMountedLayout = new javax.swing.GroupLayout(panelWeaponsMounted);
        panelWeaponsMounted.setLayout(panelWeaponsMountedLayout);
        panelWeaponsMountedLayout.setHorizontalGroup(
            panelWeaponsMountedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        panelWeaponsMountedLayout.setVerticalGroup(
            panelWeaponsMountedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        weaponsMounted.setViewportView(panelWeaponsMounted);

        javax.swing.GroupLayout panelShieldsMountedLayout = new javax.swing.GroupLayout(panelShieldsMounted);
        panelShieldsMounted.setLayout(panelShieldsMountedLayout);
        panelShieldsMountedLayout.setHorizontalGroup(
            panelShieldsMountedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        panelShieldsMountedLayout.setVerticalGroup(
            panelShieldsMountedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        shieldsMounted.setViewportView(panelShieldsMounted);

        javax.swing.GroupLayout panelHangarStationLayout = new javax.swing.GroupLayout(panelHangarStation);
        panelHangarStation.setLayout(panelHangarStationLayout);
        panelHangarStationLayout.setHorizontalGroup(
            panelHangarStationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelHangarStationLayout.setVerticalGroup(
            panelHangarStationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        mountButton.setText("Equipar");
        mountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mountButtonActionPerformed(evt);
            }
        });

        discardButton.setText("Descartar");
        discardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardButtonActionPerformed(evt);
            }
        });

        discardHangarButton.setText("Descartar Hangar Completo");
        discardHangarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardHangarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(weaponsMounted, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nombre_estacion, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(titulo_ataque)
                                    .addGap(18, 18, 18)
                                    .addComponent(ataque))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(titulo_defensa)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(defensa))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(titulo_combustible)
                                        .addComponent(titulo_medallas))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(medallas)
                                        .addComponent(combustible))))
                            .addGap(18, 18, 18)
                            .addComponent(pendingDamage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(shieldsMounted)
                        .addComponent(panelHangarStation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mountButton)
                        .addGap(18, 18, 18)
                        .addComponent(discardButton)
                        .addGap(18, 18, 18)
                        .addComponent(discardHangarButton)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pendingDamage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nombre_estacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titulo_ataque)
                            .addComponent(ataque))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titulo_defensa)
                            .addComponent(defensa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titulo_combustible)
                            .addComponent(combustible))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titulo_medallas)
                            .addComponent(medallas))))
                .addGap(18, 18, 18)
                .addComponent(weaponsMounted, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(shieldsMounted, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelHangarStation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mountButton)
                    .addComponent(discardButton)
                    .addComponent(discardHangarButton))
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mountButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mountButtonActionPerformed

    private void discardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discardButtonActionPerformed

    private void discardHangarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardHangarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discardHangarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ataque;
    private javax.swing.JLabel combustible;
    private javax.swing.JLabel defensa;
    private javax.swing.JButton discardButton;
    private javax.swing.JButton discardHangarButton;
    private javax.swing.JLabel medallas;
    private javax.swing.JButton mountButton;
    private javax.swing.JLabel nombre_estacion;
    private javax.swing.JPanel panelHangarStation;
    private javax.swing.JPanel panelShieldsMounted;
    private javax.swing.JPanel panelWeaponsMounted;
    private javax.swing.JPanel pendingDamage;
    private javax.swing.JScrollPane shieldsMounted;
    private javax.swing.JLabel titulo_ataque;
    private javax.swing.JLabel titulo_combustible;
    private javax.swing.JLabel titulo_defensa;
    private javax.swing.JLabel titulo_medallas;
    private javax.swing.JScrollPane weaponsMounted;
    // End of variables declaration//GEN-END:variables
}
