/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;
import deepspace.SpaceStationToUI;
/**
 *
 * @author Sergio
 */
public class StationDataView extends javax.swing.JPanel {

    /**
     * Creates new form SationDataView
     */
    public StationDataView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        PotenciaAtaque = new javax.swing.JLabel();
        PotenciaEscudo = new javax.swing.JLabel();
        Combustible = new javax.swing.JLabel();
        Medallas = new javax.swing.JLabel();

        Nombre.setText("jLabel1");

        PotenciaAtaque.setText("jLabel1");

        PotenciaEscudo.setText("jLabel1");

        Combustible.setText("jLabel1");

        Medallas.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombre)
                    .addComponent(PotenciaAtaque)
                    .addComponent(PotenciaEscudo)
                    .addComponent(Combustible)
                    .addComponent(Medallas))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Nombre)
                .addGap(18, 18, 18)
                .addComponent(PotenciaAtaque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PotenciaEscudo)
                .addGap(18, 18, 18)
                .addComponent(Combustible)
                .addGap(18, 18, 18)
                .addComponent(Medallas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    void setData (SpaceStationToUI s) {
        Nombre.setText(s.getName());
        PotenciaAtaque.setText("Potencia de Ataque: " + Float.toString(s.getAmmoPower()));
        PotenciaEscudo.setText("Potencia de Escudo: " + Float.toString(s.getShieldPower()));
        Combustible.setText("Nivel de Combustible: " + Float.toString(s.getFuelUnits()));
        Medallas.setText("Medallas: " + Integer.toString(s.getnMedals()));
        repaint();
        revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Combustible;
    private javax.swing.JLabel Medallas;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel PotenciaAtaque;
    private javax.swing.JLabel PotenciaEscudo;
    // End of variables declaration//GEN-END:variables
}
