/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;

import controller.Controller;
import deepspace.CardDealer;
import deepspace.SpaceStationToUI;
import java.util.ArrayList;
import deepspace.WeaponToUI;
import deepspace.ShieldToUI;
import deepspace.HangarToUI;



/**
 *
 * @author Sergio
 */
public class StationView extends javax.swing.JPanel {

    /**
     * Creates new form StationView
     */
    public StationView() {
        initComponents();
    }

    void setStation (SpaceStationToUI s) {
        StationDataView sd = new StationDataView();
        sd.setData(s);
        Data.add(sd);
        
        ListaArmas.removeAll();
        Lista_Escudos.removeAll();
        Hangar.removeAll();
        HangarToUI hangar = s.getHangar();
        if(hangar != null){
            ArrayList<WeaponToUI> weapons = s.getHangar().getWeapons();
            ArrayList<ShieldToUI> shields = s.getHangar().getShieldBoosters();
            WeaponView weaponView;
            for (WeaponToUI w : weapons) {
                weaponView = new WeaponView();
                weaponView.setWeapon(w);
                Hangar.add(weaponView);
                
            }
        }
        repaint();
        revalidate();
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Add_weapon = new javax.swing.JButton();
        Add_Shield = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaArmas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Lista_Escudos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Data = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Hangar = new javax.swing.JPanel();

        Add_weapon.setText("Add Weapon");
        Add_weapon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_weaponActionPerformed(evt);
            }
        });

        Add_Shield.setText("Add Shield");
        Add_Shield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_ShieldActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(ListaArmas);

        jScrollPane2.setViewportView(Lista_Escudos);

        jScrollPane3.setViewportView(Data);

        jScrollPane4.setViewportView(Hangar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Add_weapon)
                        .addGap(18, 18, 18)
                        .addComponent(Add_Shield))
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_weapon)
                    .addComponent(Add_Shield))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Add_weaponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_weaponActionPerformed
        // TODO add your handling code here:
        CardDealer dealer = CardDealer.getInstance();
        WeaponToUI w = dealer.nextWeapon().getUIversion();
        WeaponView v = new WeaponView();
        v.setWeapon(w);
        Hangar.add(v);
        repaint();
        revalidate();      
    }//GEN-LAST:event_Add_weaponActionPerformed

    private void Add_ShieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_ShieldActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_Add_ShieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Shield;
    private javax.swing.JButton Add_weapon;
    private javax.swing.JPanel Data;
    private javax.swing.JPanel Hangar;
    private javax.swing.JPanel ListaArmas;
    private javax.swing.JPanel Lista_Escudos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
