/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;
import deepspace.WeaponToUI;
/**
 *
 * @author Sergio
 */
public class WeaponView extends javax.swing.JPanel {

     private boolean selected = false;
    /**
     * Creates new form Weapon
     */
    public WeaponView() {
        initComponents();
        setOpaque (selected);
    }

    
     void setWeapon (WeaponToUI w) {
        Tipo.setText(w.getType().toString());
        P_n.setText(Float.toString(w.getPower()));
        U_n.setText(Integer.toString(w.getUses()));
        repaint();
    }
     
     boolean isSelected () {
        return selected;
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        Arma = new javax.swing.JLabel();
        Potencia = new javax.swing.JLabel();
        Usos = new javax.swing.JLabel();
        Tipo = new javax.swing.JLabel();
        P_n = new javax.swing.JLabel();
        U_n = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        Arma.setText("Tipo:");

        Potencia.setText("Potencia");

        Usos.setText("Usos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Arma)
                        .addGap(18, 18, 18)
                        .addComponent(Tipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(267, 267, 267))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Potencia)
                        .addGap(18, 18, 18)
                        .addComponent(P_n, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(246, 246, 246))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Usos)
                        .addGap(18, 18, 18)
                        .addComponent(U_n, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(264, 264, 264))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Arma)
                    .addComponent(Tipo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Potencia)
                    .addComponent(P_n))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usos)
                    .addComponent(U_n))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        selected = !selected;
        setOpaque (selected);
        repaint();
        
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Arma;
    private javax.swing.JLabel P_n;
    private javax.swing.JLabel Potencia;
    private javax.swing.JLabel Tipo;
    private javax.swing.JLabel U_n;
    private javax.swing.JLabel Usos;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
