/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.GUI;
import deepspace.WeaponToUI;

/**
 *
 * @author crist
 */
public class WeaponView extends javax.swing.JPanel implements CombatElementView{
    
    private boolean selected = false;
    /**
     * Creates new form WeaponView
     */
    public WeaponView() {
        initComponents();
        setOpaque(selected);
    }
    
    @Override
    public boolean isSelected () {
        return selected;
    }
    
    void setWeapon(WeaponToUI weapon){
        tipo.setText(weapon.getType().toString());
        potencia.setText(Float.toString(weapon.getPower()));
        usos.setText(Integer.toString(weapon.getUses()));
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo_tipo = new javax.swing.JLabel();
        titulo_potencia = new javax.swing.JLabel();
        titulo_usos = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        potencia = new javax.swing.JLabel();
        usos = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 102));
        setBorder(javax.swing.BorderFactory.createLineBorder(null));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        titulo_tipo.setText("Tipo :");

        titulo_potencia.setText("Potencia :");

        titulo_usos.setText("Usos :");

        tipo.setText("jLabel4");

        potencia.setText("jLabel5");

        usos.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo_potencia)
                    .addComponent(titulo_tipo)
                    .addComponent(titulo_usos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usos)
                    .addComponent(tipo)
                    .addComponent(potencia))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo_tipo)
                    .addComponent(tipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo_potencia)
                    .addComponent(potencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo_usos)
                    .addComponent(usos))
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        selected = !selected;
        setOpaque (selected);
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel potencia;
    private javax.swing.JLabel tipo;
    private javax.swing.JLabel titulo_potencia;
    private javax.swing.JLabel titulo_tipo;
    private javax.swing.JLabel titulo_usos;
    private javax.swing.JLabel usos;
    // End of variables declaration//GEN-END:variables
}
